using VoiceAgent.Domain.Entities;

namespace VoiceAgent.Infrastructure.Persistence.Seed;

public static class CampaignConfigurationSeed
{
    public static readonly IReadOnlyList<CampaignConfiguration> All =
    [
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000101"), TenantId = SeedIds.Tenant, ClientId = SeedIds.RestaurantClient, CampaignId = SeedIds.RestaurantCampaign, RequiredSlotsJson = "[\"customerName\",\"phone\",\"fulfillmentType\",\"items\",\"paymentMethod\"]", AllowedToolsJson = "[\"MenuCategorySearchTool\",\"MenuItemSearchTool\",\"DishInfoTool\",\"ListDealsTool\",\"DealSearchTool\",\"CartUpdateTool\",\"RestaurantTotalTool\",\"SaveRestaurantOrderTool\"]", HumanTransferJson = "{\"enabled\":false,\"mode\":\"Disabled\",\"fallbackWhenDisabled\":\"SaveAndClose\"}", RagSettingsJson = "{\"enabled\":true,\"topK\":4,\"minScore\":0.72,\"allowedDocumentTypes\":[\"FAQ\",\"Policy\",\"ServiceInfo\"]}" },
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000102"), TenantId = SeedIds.Tenant, ClientId = SeedIds.CourierClient, CampaignId = SeedIds.CourierCampaign, RequiredSlotsJson = "[\"customerName\",\"phone\",\"pickupAddress\",\"dropoffAddress\",\"weightKg\",\"packageType\",\"urgency\"]", AllowedToolsJson = "[\"GeocodeAddressTool\",\"DistanceCalculatorTool\",\"CourierQuoteTool\",\"SaveCourierOrderTool\"]", HumanTransferJson = "{\"enabled\":false,\"mode\":\"Disabled\",\"fallbackWhenDisabled\":\"SaveAndClose\"}" },
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000103"), TenantId = SeedIds.Tenant, ClientId = SeedIds.CabClient, CampaignId = SeedIds.CabCampaign, RequiredSlotsJson = "[\"customerName\",\"phone\",\"pickupLocation\",\"dropoffLocation\",\"pickupDateTime\",\"passengerCount\",\"vehicleType\"]", AllowedToolsJson = "[\"CabFareEstimateTool\",\"CabBookingTool\"]", HumanTransferJson = CabSeed.HumanTransferJson, ValidationRulesJson = $"{{\"fareSettings\":{CabSeed.FareSettingsJson},\"vehicleTypes\":{CabSeed.VehicleTypesJson}}}" },
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000104"), TenantId = SeedIds.Tenant, ClientId = SeedIds.DoctorClient, CampaignId = SeedIds.DoctorCampaign, RequiredSlotsJson = "[\"patientName\",\"phone\",\"reasonForVisit\",\"preferredDateTime\",\"preferredDoctor\",\"branch\"]", AllowedToolsJson = "[\"DoctorAvailabilityTool\",\"DoctorAppointmentBookingTool\",\"HumanHandoffTool\"]", HumanTransferJson = DoctorSeed.HumanTransferJson, ValidationRulesJson = DoctorSeed.DoctorDirectoryJson },
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000105"), TenantId = SeedIds.Tenant, ClientId = SeedIds.MedicareClient, CampaignId = SeedIds.MedicareCampaign, RequiredSlotsJson = "[\"leadName\",\"phone\",\"ageRange\",\"currentCoverage\",\"interestLevel\"]", AllowedToolsJson = "[\"LeadQualificationTool\",\"SalesScriptTool\",\"ObjectionHandlingTool\",\"HumanHandoffTool\"]", HumanTransferJson = "{\"enabled\":true,\"mode\":\"OnlyOnUserRequest\",\"transferNumber\":\"+441234567892\"}" },
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000106"), TenantId = SeedIds.Tenant, ClientId = SeedIds.AcaClient, CampaignId = SeedIds.AcaCampaign, RequiredSlotsJson = "[\"leadName\",\"phone\",\"currentInsuranceStatus\",\"householdSize\",\"interestLevel\"]", AllowedToolsJson = "[\"LeadQualificationTool\",\"SalesScriptTool\",\"ObjectionHandlingTool\",\"HumanHandoffTool\"]" },
        new() { Id = Guid.Parse("20000000-0000-0000-0000-000000000107"), TenantId = SeedIds.Tenant, ClientId = SeedIds.FeClient, CampaignId = SeedIds.FeCampaign, RequiredSlotsJson = "[\"leadName\",\"phone\",\"businessType\",\"monthlyRevenueRange\",\"interestLevel\"]", AllowedToolsJson = "[\"LeadQualificationTool\",\"SalesScriptTool\",\"ObjectionHandlingTool\",\"HumanHandoffTool\"]" }
    ];
}
